=== ehtishamshah24/Xml-Work/DTD/external.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT company (employee, client)>
<!ELEMENT employee (name, number, password)>
<!ELEMENT client (name, email, password)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT password (#PCDATA)>

=== ehtishamshah24/Xml-Work/DTD/externaldtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM "external.dtd" [
<!ENTITY company  "Aptech Shahra-e-Faisal">
]>
<company>
    <employee>
        <name>Saad</name>
        <number>0342-5453720</number>
        <password>$aad3705</password>

    </employee>

    <client>
        <name></name>
        <email></email>
        <password></password>
    </client>
</company>
