=== ehtishamshah24/Xml-Work/XSD/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="aptech">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="faculty" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="designation" type="xs:string"/>
                            <xs:element name="salary" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="it" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="age" type="xs:integer"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="password" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>

                </xs:element>
            </xs:sequence>
        </xs:complexType>
        
    </xs:element>
</xs:schema>

=== ehtishamshah24/Xml-Work/XSD/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<aptech
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="index.xsd">

    <faculty>
        <name>Hamza</name>
        <designation>Faculty</designation>
        <salary>120000</salary>
    </faculty>

    <faculty>
        <name>Ali</name>
        <designation>Senior Faculty</designation>
        <salary>150000</salary>
    </faculty>
    

    <it>
        <name>Saad</name>
        <age>22</age>
        <email>saad731@gmail.com</email>
        <password>$aad@137</password>
    </it>

    <it>
        <name>Fahad</name>
        <age>24</age>
        <email>fahad385@gmail.com</email>
        <password>faahd@583</password>
    </it>
    
</aptech>
